/*
 * universities.js — Türkiye'deki yükseköğretim kurumları listesi.
 * Liste kod içinde gömülüdür (uygulama çevrimdışı çalışır); güncel YÖK
 * listesiyle küçük farklar olabilir — arayüzden elle kurum eklenebilir.
 * Alanlar: ad, il, tur ("Devlet" | "Vakıf")
 */
(function (root) {
  "use strict";

  function U(ad, il, tur) { return { ad: ad, il: il, tur: tur }; }

  var UNIVERSITIES = [
    // ---- Devlet üniversiteleri ----
    U("Abdullah Gül Üniversitesi", "Kayseri", "Devlet"),
    U("Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi", "Adana", "Devlet"),
    U("Adıyaman Üniversitesi", "Adıyaman", "Devlet"),
    U("Afyon Kocatepe Üniversitesi", "Afyonkarahisar", "Devlet"),
    U("Afyonkarahisar Sağlık Bilimleri Üniversitesi", "Afyonkarahisar", "Devlet"),
    U("Ağrı İbrahim Çeçen Üniversitesi", "Ağrı", "Devlet"),
    U("Akdeniz Üniversitesi", "Antalya", "Devlet"),
    U("Aksaray Üniversitesi", "Aksaray", "Devlet"),
    U("Alanya Alaaddin Keykubat Üniversitesi", "Antalya", "Devlet"),
    U("Amasya Üniversitesi", "Amasya", "Devlet"),
    U("Anadolu Üniversitesi", "Eskişehir", "Devlet"),
    U("Ankara Üniversitesi", "Ankara", "Devlet"),
    U("Ankara Hacı Bayram Veli Üniversitesi", "Ankara", "Devlet"),
    U("Ankara Müzik ve Güzel Sanatlar Üniversitesi", "Ankara", "Devlet"),
    U("Ankara Sosyal Bilimler Üniversitesi", "Ankara", "Devlet"),
    U("Ankara Yıldırım Beyazıt Üniversitesi", "Ankara", "Devlet"),
    U("Ardahan Üniversitesi", "Ardahan", "Devlet"),
    U("Artvin Çoruh Üniversitesi", "Artvin", "Devlet"),
    U("Atatürk Üniversitesi", "Erzurum", "Devlet"),
    U("Aydın Adnan Menderes Üniversitesi", "Aydın", "Devlet"),
    U("Balıkesir Üniversitesi", "Balıkesir", "Devlet"),
    U("Bandırma Onyedi Eylül Üniversitesi", "Balıkesir", "Devlet"),
    U("Bartın Üniversitesi", "Bartın", "Devlet"),
    U("Batman Üniversitesi", "Batman", "Devlet"),
    U("Bayburt Üniversitesi", "Bayburt", "Devlet"),
    U("Bilecik Şeyh Edebali Üniversitesi", "Bilecik", "Devlet"),
    U("Bingöl Üniversitesi", "Bingöl", "Devlet"),
    U("Bitlis Eren Üniversitesi", "Bitlis", "Devlet"),
    U("Boğaziçi Üniversitesi", "İstanbul", "Devlet"),
    U("Bolu Abant İzzet Baysal Üniversitesi", "Bolu", "Devlet"),
    U("Burdur Mehmet Akif Ersoy Üniversitesi", "Burdur", "Devlet"),
    U("Bursa Teknik Üniversitesi", "Bursa", "Devlet"),
    U("Bursa Uludağ Üniversitesi", "Bursa", "Devlet"),
    U("Çanakkale Onsekiz Mart Üniversitesi", "Çanakkale", "Devlet"),
    U("Çankırı Karatekin Üniversitesi", "Çankırı", "Devlet"),
    U("Çukurova Üniversitesi", "Adana", "Devlet"),
    U("Dicle Üniversitesi", "Diyarbakır", "Devlet"),
    U("Dokuz Eylül Üniversitesi", "İzmir", "Devlet"),
    U("Düzce Üniversitesi", "Düzce", "Devlet"),
    U("Ege Üniversitesi", "İzmir", "Devlet"),
    U("Erciyes Üniversitesi", "Kayseri", "Devlet"),
    U("Erzincan Binali Yıldırım Üniversitesi", "Erzincan", "Devlet"),
    U("Erzurum Teknik Üniversitesi", "Erzurum", "Devlet"),
    U("Eskişehir Osmangazi Üniversitesi", "Eskişehir", "Devlet"),
    U("Eskişehir Teknik Üniversitesi", "Eskişehir", "Devlet"),
    U("Fırat Üniversitesi", "Elazığ", "Devlet"),
    U("Galatasaray Üniversitesi", "İstanbul", "Devlet"),
    U("Gazi Üniversitesi", "Ankara", "Devlet"),
    U("Gaziantep Üniversitesi", "Gaziantep", "Devlet"),
    U("Gaziantep İslam Bilim ve Teknoloji Üniversitesi", "Gaziantep", "Devlet"),
    U("Gebze Teknik Üniversitesi", "Kocaeli", "Devlet"),
    U("Giresun Üniversitesi", "Giresun", "Devlet"),
    U("Gümüşhane Üniversitesi", "Gümüşhane", "Devlet"),
    U("Hacettepe Üniversitesi", "Ankara", "Devlet"),
    U("Hakkari Üniversitesi", "Hakkari", "Devlet"),
    U("Harran Üniversitesi", "Şanlıurfa", "Devlet"),
    U("Hatay Mustafa Kemal Üniversitesi", "Hatay", "Devlet"),
    U("Hitit Üniversitesi", "Çorum", "Devlet"),
    U("Iğdır Üniversitesi", "Iğdır", "Devlet"),
    U("Isparta Uygulamalı Bilimler Üniversitesi", "Isparta", "Devlet"),
    U("İnönü Üniversitesi", "Malatya", "Devlet"),
    U("İskenderun Teknik Üniversitesi", "Hatay", "Devlet"),
    U("İstanbul Üniversitesi", "İstanbul", "Devlet"),
    U("İstanbul Üniversitesi-Cerrahpaşa", "İstanbul", "Devlet"),
    U("İstanbul Medeniyet Üniversitesi", "İstanbul", "Devlet"),
    U("İstanbul Teknik Üniversitesi", "İstanbul", "Devlet"),
    U("İzmir Bakırçay Üniversitesi", "İzmir", "Devlet"),
    U("İzmir Demokrasi Üniversitesi", "İzmir", "Devlet"),
    U("İzmir Kâtip Çelebi Üniversitesi", "İzmir", "Devlet"),
    U("İzmir Yüksek Teknoloji Enstitüsü", "İzmir", "Devlet"),
    U("Kafkas Üniversitesi", "Kars", "Devlet"),
    U("Kahramanmaraş İstiklal Üniversitesi", "Kahramanmaraş", "Devlet"),
    U("Kahramanmaraş Sütçü İmam Üniversitesi", "Kahramanmaraş", "Devlet"),
    U("Karabük Üniversitesi", "Karabük", "Devlet"),
    U("Karadeniz Teknik Üniversitesi", "Trabzon", "Devlet"),
    U("Karamanoğlu Mehmetbey Üniversitesi", "Karaman", "Devlet"),
    U("Kastamonu Üniversitesi", "Kastamonu", "Devlet"),
    U("Kayseri Üniversitesi", "Kayseri", "Devlet"),
    U("Kırıkkale Üniversitesi", "Kırıkkale", "Devlet"),
    U("Kırklareli Üniversitesi", "Kırklareli", "Devlet"),
    U("Kırşehir Ahi Evran Üniversitesi", "Kırşehir", "Devlet"),
    U("Kilis 7 Aralık Üniversitesi", "Kilis", "Devlet"),
    U("Kocaeli Üniversitesi", "Kocaeli", "Devlet"),
    U("Konya Teknik Üniversitesi", "Konya", "Devlet"),
    U("Kütahya Dumlupınar Üniversitesi", "Kütahya", "Devlet"),
    U("Kütahya Sağlık Bilimleri Üniversitesi", "Kütahya", "Devlet"),
    U("Malatya Turgut Özal Üniversitesi", "Malatya", "Devlet"),
    U("Manisa Celal Bayar Üniversitesi", "Manisa", "Devlet"),
    U("Mardin Artuklu Üniversitesi", "Mardin", "Devlet"),
    U("Marmara Üniversitesi", "İstanbul", "Devlet"),
    U("Mersin Üniversitesi", "Mersin", "Devlet"),
    U("Mimar Sinan Güzel Sanatlar Üniversitesi", "İstanbul", "Devlet"),
    U("Muğla Sıtkı Koçman Üniversitesi", "Muğla", "Devlet"),
    U("Munzur Üniversitesi", "Tunceli", "Devlet"),
    U("Muş Alparslan Üniversitesi", "Muş", "Devlet"),
    U("Necmettin Erbakan Üniversitesi", "Konya", "Devlet"),
    U("Nevşehir Hacı Bektaş Veli Üniversitesi", "Nevşehir", "Devlet"),
    U("Niğde Ömer Halisdemir Üniversitesi", "Niğde", "Devlet"),
    U("Ondokuz Mayıs Üniversitesi", "Samsun", "Devlet"),
    U("Ordu Üniversitesi", "Ordu", "Devlet"),
    U("Orta Doğu Teknik Üniversitesi", "Ankara", "Devlet"),
    U("Osmaniye Korkut Ata Üniversitesi", "Osmaniye", "Devlet"),
    U("Pamukkale Üniversitesi", "Denizli", "Devlet"),
    U("Recep Tayyip Erdoğan Üniversitesi", "Rize", "Devlet"),
    U("Sağlık Bilimleri Üniversitesi", "İstanbul", "Devlet"),
    U("Sakarya Üniversitesi", "Sakarya", "Devlet"),
    U("Sakarya Uygulamalı Bilimler Üniversitesi", "Sakarya", "Devlet"),
    U("Samsun Üniversitesi", "Samsun", "Devlet"),
    U("Selçuk Üniversitesi", "Konya", "Devlet"),
    U("Siirt Üniversitesi", "Siirt", "Devlet"),
    U("Sinop Üniversitesi", "Sinop", "Devlet"),
    U("Sivas Bilim ve Teknoloji Üniversitesi", "Sivas", "Devlet"),
    U("Sivas Cumhuriyet Üniversitesi", "Sivas", "Devlet"),
    U("Süleyman Demirel Üniversitesi", "Isparta", "Devlet"),
    U("Şırnak Üniversitesi", "Şırnak", "Devlet"),
    U("Tarsus Üniversitesi", "Mersin", "Devlet"),
    U("Tekirdağ Namık Kemal Üniversitesi", "Tekirdağ", "Devlet"),
    U("Tokat Gaziosmanpaşa Üniversitesi", "Tokat", "Devlet"),
    U("Trabzon Üniversitesi", "Trabzon", "Devlet"),
    U("Trakya Üniversitesi", "Edirne", "Devlet"),
    U("Türk-Alman Üniversitesi", "İstanbul", "Devlet"),
    U("Uşak Üniversitesi", "Uşak", "Devlet"),
    U("Van Yüzüncü Yıl Üniversitesi", "Van", "Devlet"),
    U("Yalova Üniversitesi", "Yalova", "Devlet"),
    U("Yıldız Teknik Üniversitesi", "İstanbul", "Devlet"),
    U("Yozgat Bozok Üniversitesi", "Yozgat", "Devlet"),
    U("Zonguldak Bülent Ecevit Üniversitesi", "Zonguldak", "Devlet"),

    // ---- Vakıf üniversiteleri ----
    U("Acıbadem Mehmet Ali Aydınlar Üniversitesi", "İstanbul", "Vakıf"),
    U("Alanya Üniversitesi", "Antalya", "Vakıf"),
    U("Altınbaş Üniversitesi", "İstanbul", "Vakıf"),
    U("Ankara Bilim Üniversitesi", "Ankara", "Vakıf"),
    U("Ankara Medipol Üniversitesi", "Ankara", "Vakıf"),
    U("Antalya Bilim Üniversitesi", "Antalya", "Vakıf"),
    U("Atılım Üniversitesi", "Ankara", "Vakıf"),
    U("Avrasya Üniversitesi", "Trabzon", "Vakıf"),
    U("Bahçeşehir Üniversitesi", "İstanbul", "Vakıf"),
    U("Başkent Üniversitesi", "Ankara", "Vakıf"),
    U("Beykent Üniversitesi", "İstanbul", "Vakıf"),
    U("Beykoz Üniversitesi", "İstanbul", "Vakıf"),
    U("Bezmiâlem Vakıf Üniversitesi", "İstanbul", "Vakıf"),
    U("Biruni Üniversitesi", "İstanbul", "Vakıf"),
    U("Çağ Üniversitesi", "Mersin", "Vakıf"),
    U("Çankaya Üniversitesi", "Ankara", "Vakıf"),
    U("Demiroğlu Bilim Üniversitesi", "İstanbul", "Vakıf"),
    U("Doğuş Üniversitesi", "İstanbul", "Vakıf"),
    U("Fatih Sultan Mehmet Vakıf Üniversitesi", "İstanbul", "Vakıf"),
    U("Fenerbahçe Üniversitesi", "İstanbul", "Vakıf"),
    U("Haliç Üniversitesi", "İstanbul", "Vakıf"),
    U("Hasan Kalyoncu Üniversitesi", "Gaziantep", "Vakıf"),
    U("Işık Üniversitesi", "İstanbul", "Vakıf"),
    U("İbn Haldun Üniversitesi", "İstanbul", "Vakıf"),
    U("İhsan Doğramacı Bilkent Üniversitesi", "Ankara", "Vakıf"),
    U("İstanbul 29 Mayıs Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Arel Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Atlas Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Aydın Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Bilgi Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Esenyurt Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Galata Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Gedik Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Gelişim Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Kent Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Kültür Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Medipol Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Okan Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Rumeli Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Sabahattin Zaim Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Sağlık ve Teknoloji Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Ticaret Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Topkapı Üniversitesi", "İstanbul", "Vakıf"),
    U("İstanbul Yeni Yüzyıl Üniversitesi", "İstanbul", "Vakıf"),
    U("İstinye Üniversitesi", "İstanbul", "Vakıf"),
    U("İzmir Ekonomi Üniversitesi", "İzmir", "Vakıf"),
    U("İzmir Tınaztepe Üniversitesi", "İzmir", "Vakıf"),
    U("Kadir Has Üniversitesi", "İstanbul", "Vakıf"),
    U("Kapadokya Üniversitesi", "Nevşehir", "Vakıf"),
    U("Koç Üniversitesi", "İstanbul", "Vakıf"),
    U("Kocaeli Sağlık ve Teknoloji Üniversitesi", "Kocaeli", "Vakıf"),
    U("Konya Gıda ve Tarım Üniversitesi", "Konya", "Vakıf"),
    U("KTO Karatay Üniversitesi", "Konya", "Vakıf"),
    U("Lokman Hekim Üniversitesi", "Ankara", "Vakıf"),
    U("Maltepe Üniversitesi", "İstanbul", "Vakıf"),
    U("MEF Üniversitesi", "İstanbul", "Vakıf"),
    U("Mudanya Üniversitesi", "Bursa", "Vakıf"),
    U("Nişantaşı Üniversitesi", "İstanbul", "Vakıf"),
    U("Nuh Naci Yazgan Üniversitesi", "Kayseri", "Vakıf"),
    U("OSTİM Teknik Üniversitesi", "Ankara", "Vakıf"),
    U("Özyeğin Üniversitesi", "İstanbul", "Vakıf"),
    U("Piri Reis Üniversitesi", "İstanbul", "Vakıf"),
    U("Sabancı Üniversitesi", "İstanbul", "Vakıf"),
    U("Sanko Üniversitesi", "Gaziantep", "Vakıf"),
    U("TED Üniversitesi", "Ankara", "Vakıf"),
    U("TOBB Ekonomi ve Teknoloji Üniversitesi", "Ankara", "Vakıf"),
    U("Toros Üniversitesi", "Mersin", "Vakıf"),
    U("Türk Hava Kurumu Üniversitesi", "Ankara", "Vakıf"),
    U("Ufuk Üniversitesi", "Ankara", "Vakıf"),
    U("Üsküdar Üniversitesi", "İstanbul", "Vakıf"),
    U("Yaşar Üniversitesi", "İzmir", "Vakıf"),
    U("Yeditepe Üniversitesi", "İstanbul", "Vakıf"),
    U("Yüksek İhtisas Üniversitesi", "Ankara", "Vakıf")
  ];

  var api = { UNIVERSITIES: UNIVERSITIES };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.Universities = api;
})(typeof self !== "undefined" ? self : this);
